//Users
export const USER_LOGIN= "USER_LOGIN";
export const USER_REGISTER= "USER_REGISTER";
export const USER_REGISTER_STATUS= "USER_REGISTER_STATUS";
export const USER_LOGOUT= "USER_LOGOUT";


//Products
export const CREATE_PRODUCT= "CREATE_PRODUCT";
export const EDIT_PRODUCT= "CREATE_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const SORT_BY_STOCK = "SORT_BY_STOCK";
export const SORT_BY_NAME = "SORT_BY_NAME";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

//Company
export const COMPANY_REGISTER= "COMPANY_REGISTER";
export const GET_COMPANY = "GET_COMPANY";

//Sales
export const GET_SALES = "GET_SALES";
export const CREATE_SALE = "CREATE_SALE"
